# Server config
web:
  host: 127.0.0.1
  port: 8080
  timeout:
    read: 10
    write: 10
    server: 5
database:
  user: postgres
  password: postgres
  host: localhost
  name: postgres
  disabletls: true
redis:
  address: localhost
  port: 6379
  db: 0
